services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "${API_GATEWAY_PORT}:3000"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  order-worker:
    build:
      context: ./order-worker
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "${ORDER_WORKER_PORT}:3000"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}

      DB_HOST: ${ORDER_DB_HOST}
      DB_PORT: ${ORDER_DB_PORT}
      DB_USER: ${ORDER_DB_USER}
      DB_PASS: ${ORDER_DB_PASS}
      DB_NAME: ${ORDER_DB_NAME}
    volumes:
      - ./order-worker:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - emart-db

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "${AUTH_SERVICE_PORT}:3000"
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}

      DB_HOST: ${AUTH_DB_HOST}
      DB_PORT: ${AUTH_DB_PORT}
      DB_USER: ${AUTH_DB_USER}
      DB_PASS: ${AUTH_DB_PASS}
      DB_NAME: ${AUTH_DB_NAME}
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - auth-db

  emart-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${EMART_DB_USER}
      POSTGRES_PASSWORD: ${EMART_DB_PASS}
      POSTGRES_DB: ${EMART_DB_NAME}
    ports:
      - "${EMART_DB_PORT}:5432"
    volumes:
      - emart_pgdata:/var/lib/postgresql/data

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - emart-db
      - auth-db

volumes:
  emart_pgdata:
  auth_pgdata:
